//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LO_THUOC()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
        }
    
        public int id_lo_thuoc { get; set; }
        public int id_thuoc { get; set; }
        public string so_lo { get; set; }
        public Nullable<System.DateTime> han_su_dung { get; set; }
        public Nullable<System.DateTime> ngay_san_xuat { get; set; }
        public Nullable<int> so_luong_nhap { get; set; }
        public Nullable<int> so_luong_ton { get; set; }
        public Nullable<int> gia_nhap { get; set; }
        public Nullable<int> tieu_huy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
