//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NHA_THUOCEntities : DbContext
    {
        public NHA_THUOCEntities()
            : base("name=NHA_THUOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual DbSet<DANH_MUC_THUOC> DANH_MUC_THUOC { get; set; }
        public virtual DbSet<DIA_DIEM_NHA_THUOC> DIA_DIEM_NHA_THUOC { get; set; }
        public virtual DbSet<LO_THUOC> LO_THUOC { get; set; }
        public virtual DbSet<LOAI_THUOC> LOAI_THUOC { get; set; }
        public virtual DbSet<PHAN_QUYEN> PHAN_QUYEN { get; set; }
        public virtual DbSet<PHUONG_XA> PHUONG_XA { get; set; }
        public virtual DbSet<QUAN_HUYEN> QUAN_HUYEN { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<TINH_THANH> TINH_THANH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
    }
}
