//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_HUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUAN_HUYEN()
        {
            this.PHUONG_XA = new HashSet<PHUONG_XA>();
        }
    
        public int id_quan_huyen { get; set; }
        public string ten { get; set; }
        public Nullable<int> id_tinh_thanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUONG_XA> PHUONG_XA { get; set; }
        public virtual TINH_THANH TINH_THANH { get; set; }
    }
}
