//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public int id_chi_tiet_hoa_don { get; set; }
        public int id_hoa_don { get; set; }
        public Nullable<int> id_lo_thuoc { get; set; }
        public int so_luong { get; set; }
        public Nullable<int> don_gia { get; set; }
        public Nullable<int> thanh_tien { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual LO_THUOC LO_THUOC { get; set; }
    }
}
