//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA_DIEM_NHA_THUOC
    {
        public int id_dia_diem { get; set; }
        public string ten_nha_thuoc { get; set; }
        public string thanh_pho_tinh { get; set; }
        public string quan_huyen { get; set; }
        public string so_duong_ten_duong { get; set; }
    }
}
