//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONG_XA
    {
        public int id_phuong_xa { get; set; }
        public string ten { get; set; }
        public Nullable<int> id_quan_huyen { get; set; }
    
        public virtual QUAN_HUYEN QUAN_HUYEN { get; set; }
    }
}
