//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAI_KHOAN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int id_tai_khoan { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public string ho_ten { get; set; }
        public string quyen_han { get; set; }
        public int id_quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual PHAN_QUYEN PHAN_QUYEN { get; set; }
    }
}
