//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_Nhom_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.LO_THUOC = new HashSet<LO_THUOC>();
        }
    
        public int id_thuoc { get; set; }
        public int id_danh_muc { get; set; }
        public Nullable<int> id_loai_thuoc { get; set; }
        public string ten_thuoc { get; set; }
        public string hang { get; set; }
        public string hoat_chat { get; set; }
        public string don_vi_tinh { get; set; }
        public string dang_bao_che { get; set; }
        public string ham_luong { get; set; }
        public string cong_dung { get; set; }
        public string lieu_dung { get; set; }
        public string chong_chi_dinh { get; set; }
        public Nullable<int> gia_ban { get; set; }
        public string anh_thuoc { get; set; }
    
        public virtual DANH_MUC_THUOC DANH_MUC_THUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LO_THUOC> LO_THUOC { get; set; }
        public virtual LOAI_THUOC LOAI_THUOC { get; set; }
    }
}
